input:
  stdin: {}
pipeline:
  processors:
    - jev_decision: {}
output:
  switch:
    cases:
      - check: errored()
        output:
          file:
            path: failed-inputs.txt
            codec: lines
      - output:
          stdout:
            codec: lines
